version: '3.8'

services:
  candle-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/main.go
    environment:
      - ENV=development
      - LOG_LEVEL=debug
    ports:
      - "8080:8080"
    networks:
      - candle-network

networks:
  candle-network:
    driver: bridge
